services:
  postgres:
    image: postgres:18
    container_name: nest-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_db
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql

  # docker exec -it nest-postgres psql -U postgres

  # docker exec -it my-redis redis-cli

  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
