services:
  postgres:
    image: postgres:18
    container_name: nest-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_db
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql

volumes:
  postgres_data:
